# Generated by Django 4.1.2 on 2022-10-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('race', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
